version: '3.8'

services:

  backend:
    build: ./backend
    container_name: laudo_backend
    env_file:
      - ./.env       
    environment:
      - PYTHONUNBUFFERED=1 
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    
    command: gunicorn --bind 0.0.0.0:5000 --workers ${GUNICORN_WORKERS} --timeout ${GUNICORN_TIMEOUT}  --log-level=debug --reload run:app
  # Serviço do Frontend (React + Nginx)
  frontend:
    build: ./frontend 
    container_name: laudo_frontend
    ports:
      - "3000:80"     
    depends_on:
      - backend       